DROP TABLE IF EXISTS waiter;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS manager;
DROP TABLE IF EXISTS chef;
DROP TABLE IF EXISTS dish;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS ingredient;